<?php

declare(strict_types=1);

require __DIR__ . '/TestHarness.php';

$root=dirname(__DIR__);$t=new TestHarness();$read=static fn(string $path):string=>(string)file_get_contents($root.'/'.$path);

$t->test('Integration readiness is bound to explicit deployment environment',function()use($read):void{$code=$read('src/Application/IntegrationService.php');TestHarness::assertTrue(str_contains($code,'deploymentEnvironment'));TestHarness::assertTrue(str_contains($code,'$environment === (string)$row[\'environment_name\']'));TestHarness::assertTrue(str_contains($code,'CF-06 deployment environment is not explicitly configured'));});
$t->test('Production runtime activation requires separate release evidence',function()use($read):void{$code=$read('src/Application/HealthService.php');foreach(['staging_acceptance','rollback_restore_rehearsal','exact_package_parity','security_privacy_acceptance','accessibility_acceptance','performance_acceptance','slto_verify_production_activation_evidence'] as $needle){TestHarness::assertTrue(str_contains($code,$needle),$needle);}});
$t->test('QA pass evidence requires matching hashes and latest-state semantics',function()use($read):void{$code=$read('src/Application/QaEvidenceService.php');TestHarness::assertTrue(str_contains($code,"'pass' === \$result"));TestHarness::assertTrue(str_contains($code,'expected and actual hashes differ'));TestHarness::assertTrue(str_contains($code,'$latest[$testId]'));TestHarness::assertTrue(str_contains($code,'pluginVersion'));TestHarness::assertTrue(str_contains($code,'buildSha'));});
$t->test('Job queue reclaims expired running leases and dead-letters exhausted crashes',function()use($read):void{$code=$read('src/Infrastructure/JobQueue.php');TestHarness::assertTrue(str_contains($code,"status='running' AND lease_until IS NOT NULL AND lease_until<"));TestHarness::assertTrue(str_contains($code,'expired_worker_lease'));TestHarness::assertTrue(str_contains($code,"'reclaimed'=>0"));});
$t->test('Privacy erasure uses unique request identity and exports retained actor metadata',function()use($read):void{$code=$read('src/Application/PrivacyService.php');foreach(['privacy-erasure-','request_id','unit_roles','resources_actor_metadata','terminology_actor_metadata','style_guide_actor_metadata','vendor_job_actor_metadata','bundle_actor_metadata','retained_audit_metadata','immutable_audit_actor_metadata'] as $needle){TestHarness::assertTrue(str_contains($code,$needle),$needle);}});
$t->test('Translation comments require current assignment rather than stale unit role IDs',function()use($read):void{$code=$read('src/Application/TranslationService.php');TestHarness::assertTrue(str_contains($code,'assignedActorIsCurrent'));TestHarness::assertTrue(str_contains($code,'Only currently assigned translation participants may comment'));TestHarness::assertTrue(str_contains($code,"'status'=>'active'"));});
$t->test('Bundle QA is frozen after approval and rechecked at activation',function()use($read):void{$code=$read('src/Application/BundleService.php');TestHarness::assertTrue(str_contains($code,"array('approved','staged','canary','active','superseded','rolled_back','invalidated')"));TestHarness::assertTrue(substr_count($code,'assertCurrentHumanQa')>=3);});
$t->test('Machine translation is bound to an active governed provider record',function()use($read):void{$code=$read('src/Application/MachineTranslationService.php');TestHarness::assertTrue(substr_count($code,'assertActiveProvider')>=4);TestHarness::assertTrue(str_contains($code,"'active'!==(string)\$row['status']"));TestHarness::assertTrue(str_contains($code,'provider-region binding'));});
$t->test('Active provider configuration cannot drift without disable and reapproval',function()use($read):void{$code=$read('src/Application/ProviderService.php');TestHarness::assertTrue(str_contains($code,'An active provider must be disabled before governance-relevant configuration is changed'));});
$t->test('Terminology and style-guide storage bounds are explicit',function()use($read):void{$code=$read('src/Application/TerminologyService.php');foreach(['strlen($concept)>80','strlen($domain)>80','strlen($source)>191','strlen($approved)>191','prohibited terminology variant exceeds','Style guide domain exceeds'] as $needle){TestHarness::assertTrue(str_contains($code,$needle),$needle);}});
$t->test('Release approval step-up timestamp is strict UTC',function()use($read):void{$code=$read('src/Application/ReleaseApprovalService.php');TestHarness::assertTrue(str_contains($code,'strictUtcTimestamp'));TestHarness::assertTrue(str_contains($code,"Y-m-d\\TH:i:s\\Z"));TestHarness::assertTrue(!str_contains($code,'strtotime($stepUpAt)'));});
$t->test('Expired idempotency records are retired synchronously before reuse',function()use($read):void{$code=$read('src/Infrastructure/Repository/LocalizationRepository.php');TestHarness::assertTrue(str_contains($code,'Expired idempotency state could not be retired'));TestHarness::assertTrue(str_contains($code,'expires_at<%s'));});
$t->test('Public locale helpers respect runtime-disabled state',function()use($read):void{$code=$read('src/functions.php');TestHarness::assertTrue(substr_count($code,'Plugin::runtimeEnabled()')>=4);TestHarness::assertTrue(str_contains($code,"'status'=>'runtime_disabled'"));});

$t->finish();
